spring.application.name: springboot-graphql
spring:
  datasource:
    url: jdbc:h2:mem:empdata
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    showSql: true
    databasePlatform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddlAuto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true